CFLAGS += -DHAVE_CONFIG_H -D__Nautilus__ -Iinclude/libevent/ -Iinclude/net/lwip/ -Iinclude/net/lwip/posix/

obj-y += \
	listener.o \
	evport.o \
	signal.o \
	bufferevent_openssl.o \
	evrpc.o \
	buffer.o \
	devpoll.o \
	evthread_pthread.o \
	bufferevent.o \
	bufferevent_sock.o \
	evthread_win32.o \
	poll.o \
	evthread.o \
	strlcpy.o \
	epoll.o \
	bufferevent_pair.o \
	epoll_sub.o \
	bufferevent_filter.o \
	kqueue.o \
	event.o \
	arc4random.o \
	evutil_rand.o \
	evdns.o \
	evutil.o \
	http.o \
	event_tagging.o \
	bufferevent_async.o \
	evmap.o \
	bufferevent_ratelim.o \
	select.o \
	evutil_time.o \

    # \
    log.o \
	win32select.o \
	event_iocp.o \
	buffer_iocp.o \
