obj-y += asm/ \
		pisces_lock.o \
		pisces_ringbuf.o \
		test.o \
		mwait.o \
		numa.o \
		init.o \
		main.o \
		shutdown.o \
		smp.o \
		early_mem.o \
        pisces_ctrl.o \
        pisces_xbuf.o
		
