obj-y += \
	nautilus/ \
	arch/ \
	asm/ \
	dev/ \
        fs/  \
        gc/  \
	rt/ \
        net/ \
	acpi/ \
	test/ \
    #libevent-2.1.11/ \
    #memcached-1.5.19/ 

obj-$(NAUT_CONFIG_CXX_SUPPORT) += cxx/
obj-$(NAUT_CONFIG_LEGION_RT) += legion_runtime/
obj-$(NAUT_CONFIG_LOAD_LUA) += lua_src/
obj-$(NAUT_CONFIG_RUST_SUPPORT) += rust/
