CFLAGS+= -D__Nautilus__ -DNEED_ALIGN -Iinclude/net/lwip

obj-y += assoc.o \
    util.o \
    hash.o\
    jenkins_hash.o \
    murmur3_hash.o \
    slabs.o \
    items.o \
    thread.o \
    memcached.o \
