CFLAGS += -DHAVE_CONFIG_H -D__Nautilus__ -Iinclude/net/lwip -Iinclude/net/lwip/posix -Iinclude/libevent

obj-y += daemon.o \
	thread.o \
	slab_automove.o \
	extstore.o \
	memcached.o \
	crc32c.o \
	murmur3_hash.o \
	assoc.o \
	storage.o \
	util.o \
	logger.o \
	stats.o \
	jenkins_hash.o \
	slabs.o \
	itoa_ljust.o \
	authfile.o \
	hash.o \
	restart.o \
	bipbuffer.o \
	tls.o \
	cache.o \
	crawler.o \
	items.o \
    \
    nautilus_priv.o
	#linux_priv.o \
	solaris_priv.o \
	freebsd_priv.o \
	openbsd_priv.o \
	\
    sasl_defs.o \
    \
    slab_automove_extstore.c \
    \
	timedrun.o \
    \
	testapp.o \
    \
    sizes.o
